http:
  port: ${PORT_HTTP:-8080}
  hostname: '0.0.0.0'
https:
  port: ${PORT_HTTPS:-443}
  hostname: '0.0.0.0'
  tls:
    "default":
      key: ${SSL_KEY_PATH}
      cert: ${SSL_CERT_PATH}

####### API ENDPOINTS DEFINITION ########
apiEndpoints:
  ####### ACCOUNT API PUBLIC ########
  accountPublic:
    - host: '*'
      paths: ['/v1/auth']
      methods: ['POST']

    - host: '*'
      paths: ['/v1/auth/forgot']
      methods: ['POST']

    - host: '*'
      paths: ['/v1/auth/verify-email']
      methods: ['POST']

    - host: '*'
      paths: ['/v1/auth/password']
      methods: ['PATCH']
  ####### ACCOUNT API PUBLIC END ########

  ####### ACCOUNT API PRIVATE ########
  accountPrivate:
    ## ENDPOINT TO DELETE USERS ##
    - host: '*'
      paths: ['/v1/users/:user_id']
      methods: ['DELETE']
      scopes: ['admins:delete','healthprofessionals:delete','patients:delete']
    ###############################

    ## ENDPOINTS TO MANAGE ADMIN TYPE USERS ##
    - host: '*'
      paths: ['/v1/admins']
      methods: ['POST']
      scopes: ['admins:create']

    - host: '*'
      paths: ['/v1/admins']
      methods: ['GET']
      scopes: ['admins:readAll']

    - host: '*'
      paths: ['/v1/admins/:admin_id']
      methods: ['GET']
      scopes: ['admins:read']

    - host: '*'
      paths: ['/v1/admins/:admin_id']
      methods: ['PATCH']
      scopes: ['admins:update']
    ###############################

    ## ENDPOINTS TO MANAGE HEALTHPROFESSIONAL TYPE USERS ##
    - host: '*'
      paths: ['/v1/healthprofessionals']
      methods: ['POST']
      scopes: ['healthprofessionals:create']

    - host: '*'
      paths: ['/v1/healthprofessionals']
      methods: ['GET']
      scopes: ['healthprofessionals:readAll']

    - host: '*'
      paths: ['/v1/healthprofessionals/:healthprofessional_id']
      methods: ['GET']
      scopes: ['healthprofessionals:read']

    - host: '*'
      paths: ['/v1/healthprofessionals/:healthprofessional_id']
      methods: ['PATCH']
      scopes: ['healthprofessionals:update']
    ###############################

    ## ENDPOINT TO RECOVER PILOTSTUDIES ASSOCIED  ##
    - host: '*'
      paths: ['/v1/healthprofessionals/:healthprofessional_id/pilotstudies']
      methods: ['GET']
      scopes: ['pilots:read']
    ###############################

    ## ENDPOINTS TO MANAGE PATIENTS ##
    - host: '*'
      paths: ['/v1/patients']
      methods: ['POST']
      scopes: ['patients:create']

    - host: '*'
      paths: ['/v1/patients']
      methods: ['GET']
      scopes: ['patients:readAll']

    - host: '*'
      paths: ['/v1/patients/:patient_id']
      methods: ['GET']
      scopes: ['patients:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id']
      methods: ['PATCH']
      scopes: ['patients:update']
    ######################################

    ## ENDPOINT TO RECOVER ALL PILOTS FROM PATIENT ##
    - host: '*'
      paths: ['/v1/patients/:patient_id/pilotstudies']
      methods: ['GET']
      scopes: ['pilots:read']
    ######################################

    ## ENDPOINTS TO MANAGE PILOT STUDIES ##
    - host: '*'
      paths: ['/v1/pilotstudies']
      methods: ['POST']
      scopes: ['pilots:create']

    - host: '*'
      paths: ['/v1/pilotstudies']
      methods: ['GET']
      scopes: ['pilots:readAll']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id']
      methods: ['GET']
      scopes: ['pilots:read']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id']
      methods: ['PATCH']
      scopes: ['pilots:update']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id']
      methods: ['DELETE']
      scopes: ['pilots:delete']
    ######################################

    ## ENDPOINTS TO MANAGE HEALTH PROFESSIONALS ASSOCIATION WITH A PILOT STUDY ##
    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/healthprofessionals']
      methods: ['GET']
      scopes: ['healthprofessionals:read']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/healthprofessionals/:healthprofessional_id']
      methods: ['POST']
      scopes: ['pilots:update']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/healthprofessionals/:healthprofessional_id']
      methods: ['DELETE']
      scopes: ['pilots:update']
    ######################################

    ## ENDPOINTS TO MANAGE PATIENTS ASSOCIATION WITH A PILOT STUDY ##
    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/patients']
      methods: ['GET']
      scopes: ['patients:read']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/patients/:patient_id']
      methods: ['POST']
      scopes: ['pilots:update']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/patients/:patient_id']
      methods: ['DELETE']
      scopes: ['pilots:delete']
    ######################################

  ################ ACCOUNT API PRIVATE END #####################################

  ####### EHR API PRIVATE ########
  ehrPrivate:
    ## ENDPOINTS TO MANAGE NUTRITION QUESTIONNAIRES ##
    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/questionnaires']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/questionnaires']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/questionnaires/last']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/questionnaires/:questionnaire_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/questionnaires/:questionnaire_id']
      methods: ['DELETE']
      scopes: ['forms:delete']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/questionnaires/:questionnaire_id/:resource_name']
      methods: ['PUT']
      scopes: ['forms:update']
    ###############################

    ## ENDPOINTS TO MANAGE ODONTOLOGICAL QUESTIONNAIRES ##
    - host: '*'
      paths: ['/v1/patients/:patient_id/odontological/questionnaires']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/questionnaires']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/odontological/questionnaires/last']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/odontological/questionnaires/:questionnaire_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/odontological/questionnaires/:questionnaire_id']
      methods: ['DELETE']
      scopes: ['forms:delete']

    - host: '*'
      paths: ['/v1/patients/:patient_id/odontological/questionnaires/:questionnaire_id/:resource_name']
      methods: ['PUT']
      scopes: ['forms:update']
    ###############################

    ## ENDPOINT TO RECOVER ALL QUESTIONNAIRES TYPES ##
    - host: '*'
      paths: ['/v1/questionnaires/types']
      methods: ['GET']
      scopes: ['forms:read']
    ###############################

  ############### EHR API PRIVATE END ##########################################

  ####### MHEALTH API PRIVATE ########
  mhealthPrivate:
    ## ENDPOINTS TO MANAGE MEASUREMENTS ##
    - host: '*'
      paths: ['/v1/measurements']
      methods: ['GET']
      scopes: ['measurements:readAll']

    - host: '*'
      paths: ['/v1/measurements/types']
      methods: ['GET']
      scopes: ['measurements:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/measurements']
      methods: ['POST']
      scopes: ['measurements:create']

    - host: '*'
      paths: ['/v1/patients/:patient_id/measurements']
      methods: ['GET']
      scopes: ['measurements:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/measurements/last']
      methods: ['GET']
      scopes: ['measurements:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/measurements/:measurement_id']
      methods: ['GET']
      scopes: ['measurements:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/measurements/:measurement_id']
      methods: ['DELETE']
      scopes: ['measurements:delete']
    ###############################

    ## ENDPOINTS TO MANAGE DEVICES ##
    - host: '*'
      paths: ['/v1/patients/:patient_id/devices']
      methods: ['POST']
      scopes: ['devices:create']

    - host: '*'
      paths: ['/v1/patients/:patient_id/devices']
      methods: ['GET']
      scopes: ['devices:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/devices/:device_id']
      methods: ['GET']
      scopes: ['devices:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/devices/:device_id']
      methods: ['DELETE']
      scopes: ['devices:delete']
    ###############################

  ############### MHEALTH API PRIVATE END ##########################################

  ####### ANALYTICS API PRIVATE ########
  analyticsPrivate:
    ## ENDPOINTS TO MANAGE NUTRITIONAL EVALUATIONS ##
    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/evaluations']
      methods: ['POST']
      scopes: ['evaluations:create']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/evaluations']
      methods: ['GET']
      scopes: ['evaluations:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/evaluations/:evaluation_id']
      methods: ['GET']
      scopes: ['evaluations:read']

    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/evaluations/:evaluation_id']
      methods: ['DELETE']
      scopes: ['evaluations:delete']
    ####################################

    ## ENDPOINTS TO MANAGE COUNSELINGS FOR A NUTRITIONAL EVALUATIONS ##
    - host: '*'
      paths: ['/v1/patients/:patient_id/nutritional/evaluations/:evaluation_id/counselings']
      methods: ['POST']
      scopes: ['evaluations:update']
    ####################################

    ## ENDPOINT TO RECOVER ALL NUTRITIONAL EVALUATIONS FOR A PILOTSTUDY ##
    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/nutritional/evaluations']
      methods: ['GET']
      scopes: ['evaluations:read']
    ####################################

    ## ENDPOINT TO RECOVER ALL EVALUATIONS FOR A HEALTHPROFESSIONAL ##
    - host: '*'
      paths: ['/v1/healthprofessionals/:healthprofessional_id/nutritional/evaluations']
      methods: ['GET']
      scopes: ['evaluations:read']
    ###############################

    ## ENDPOINTS TO MANAGE EVALUATIONS DATA FOR A PILOTSTUDY ##
    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/data']
      methods: ['POST']
      scopes: ['evaluations:create']

    - host: '*'
      paths: ['/v1/pilotstudies/:pilotstudy_id/data']
      methods: ['GET']
      scopes: ['evaluations:read']
    ####################################

  ############### ANALYTICS API PRIVATE END ##########################################

  ####### NOTIFICATION API PRIVATE ########
  notificationPrivate:
    ## ENDPOINTS TO MANAGE E-MAIL NOTIFICATION ##
    - host: '*'
      paths: ['/v1/users/:user_id/emails']
      methods: ['POST']
      scopes: ['notifications:create']

    - host: '*'
      paths: ['/v1/users/:user_id/emails']
      methods: ['GET']
      scopes: ['notifications:read']

    - host: '*'
      paths: ['/v1/users/:user_id/emails/:email_id']
      methods: ['GET']
      scopes: ['notifications:read']

    - host: '*'
      paths: ['/v1/users/:user_id/emails/:email_id']
      methods: ['DELETE']
      scopes: ['notifications:delete']
    ####################################

  ############### NOTIFICATION API PRIVATE END ##########################################

####### SERVICE ENDPOINTS DEFINITIONS ########
serviceEndpoints:
  accountService:
    url: ${ACCOUNT_SERVICE:-https://localhost:3001}

  mhealthService:
    url: ${MHEALTH_SERVICE:-https://localhost:4001}

  ehrService:
    url: ${EHR_SERVICE:-https://localhost:5001}

  analyticsService:
    url: ${ANALYTICS_SERVICE:-htts://localhost:6001}

  notificationService:
    url: ${NOTIFICATION_SERVICE:-https://localhost:7001}

####### POLICIES USED IN PIPELINES DEFINITION ########
policies:
  - log
  - proxy
  - rate-limit
  - jwtScopes-policy
  - jwt-policy
  - auth-policy
  - body-parser-policy
  - delete-user-policy

####### PIPELINES DEFINITION ########
pipelines:
  ##################### PIPELINE PRIVATE ACCOUNT SERVICE ####################
  - name: privateAcountServicePipeline
    apiEndpoints:
      - accountPrivate
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - body-parser-policy:
      - jwt-policy:
          - action:
              secretOrPublicKeyFile: ${JWT_PUBLIC_KEY_PATH:-./.certs/jwt.pem}
              issuer: ${ISSUER:-haniot}
      - jwtScopes-policy:
      - delete-user-policy:
          - condition:
              name: 'regex-path-method'
              #regexPath é uma expressão regular
              regexPath: '^(\/v1/users\/)[a-fA-F0-9]{24}\/{0,1}$'
              method: 'DELETE'
            action:
              urlDeleteService: ${ACCOUNT_SERVICE:-https://localhost:3001}/v1/users
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              secure: false
              timeout: 10000
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PUBLIC ACCOUNT SERVICE ####################
  - name: publicAccountServicePipeline
    apiEndpoints:
      - accountPublic
    policies:
      - log:
          - action:
              message: '${req.method} ${req.originalUrl} Hostname:${req.hostname} IP:${req.ip}'
      - body-parser-policy:
      - rate-limit:
          - action:
              max: 5
              windowMs: 3600000
              rateLimitBy: "${req.hostname} ${req.body.email}"
              statusCode: 429
              message: 'The fee limit for requests has been exceeded. Try again after 1 hour.'
              headers: true

      - auth-policy:
          - condition:
              name: 'regex-path-method'
              #regexPath é uma expressão regular
              regexPath: '^(/v1/auth)$'
              method: 'POST'
            action:
              urlAuthService: ${ACCOUNT_SERVICE:-https://localhost:3001}/v1/auth
              secretOrPublicKeyFile: ${JWT_PUBLIC_KEY_PATH:-./.certs/jwt.pem}
              issuer: ${ISSUER:-haniot}
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              secure: false
              timeout: 10000
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PRIVATE EHR SERVICE ####################
  - name: privateEHRServicePipeline
    apiEndpoints:
      - ehrPrivate
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - jwt-policy:
          - action:
              secretOrPublicKeyFile: ${JWT_PUBLIC_KEY_PATH:-./.certs/jwt.pem}
              issuer: ${ISSUER:-haniot}
      - jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              secure: false
              timeout: 10000
              serviceEndpoint: ehrService
  ###########################################################################

  ##################### PIPELINE PRIVATE MHEALTH SERVICE ####################
  - name: privateMHEALTHServicePipeline
    apiEndpoints:
      - mhealthPrivate
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - jwt-policy:
          - action:
              secretOrPublicKeyFile: ${JWT_PUBLIC_KEY_PATH:-./.certs/jwt.pem}
              issuer: ${ISSUER:-haniot}
      - jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              secure: false
              timeout: 10000
              serviceEndpoint: mhealthService
  ###########################################################################

  ##################### PIPELINE PRIVATE ANALYTIVS SERVICE ####################
  - name: privateAnalyticsServicePipeline
    apiEndpoints:
      - analyticsPrivate
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - body-parser-policy:
      - jwt-policy:
          - action:
              secretOrPublicKeyFile: ${JWT_PUBLIC_KEY_PATH:-./.certs/jwt.pem}
              issuer: ${ISSUER:-haniot}
      - jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              secure: false
              timeout: 10000
              serviceEndpoint: analyticsService
  ###########################################################################

  ##################### PIPELINE PRIVATE NOTIFICATION SERVICE ####################
  - name: privateNotificationServicePipeline
    apiEndpoints:
      - notificationPrivate
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - jwt-policy:
          - action:
              secretOrPublicKeyFile: ${JWT_PUBLIC_KEY_PATH:-./.certs/jwt.pem}
              issuer: ${ISSUER:-haniot}
      - jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              secure: false
              timeout: 10000
              serviceEndpoint: notificationService
###########################################################################
