http:
  port: ${PORT_HTTP:-8080}
  hostname: 0.0.0.0

####### API ENDPOINTS DEFINITION ########
apiEndpoints:

  ####### ACCOUNT API PUBLIC ########
  accountPublic:
    - host: '*'
      paths: ['/users/:user_id/password']
      methods: ['PATCH']

    - host: '*'
      paths: ['/auth']
      methods: ['POST']
  ####### ACCOUNT API PUBLIC END ########

  ####### ACCOUNT API PRIVATE ########
  accountPrivate:
    ## ENDPOINTS TO MANAGE USERS ##
    - host: '*'
      paths: ['/users/admins']
      methods: ['POST']
      scopes: ['admins:create']

    - host: '*'
      paths: ['/users/admins']
      methods: ['GET']
      scopes: ['admins:readAll']

    - host: '*'
      paths: ['/users/admins/:admin_id']
      methods: ['GET']
      scopes: ['admins:read']

    - host: '*'
      paths: ['/users/admins/:admin_id']
      methods: ['PATCH']
      scopes: ['admins:update']

    - host: '*'
      paths: ['/users/healthprofessionals']
      methods: ['POST']
      scopes: ['healthprofessionals:create']

    - host: '*'
      paths: ['/users/healthprofessionals']
      methods: ['GET']
      scopes: ['healthprofessionals:readAll']

    - host: '*'
      paths: ['/users/healthprofessionals/:healthprofessional_id']
      methods: ['GET']
      scopes: ['healthprofessionals:read']

    - host: '*'
      paths: ['/users/healthprofessionals/:healthprofessional_id']
      methods: ['PATCH']
      scopes: ['healthprofessionals:update']

    - host: '*'
      paths: ['/users/:user_id']
      methods: ['DELETE']
      scopes: ['admins:delete','healthprofessionals:delete','patients:delete']
    ###############################

    ## ENDPOINTS TO MANAGE PATIENTS ##
    - host: '*'
      paths: ['/users/patients']
      methods: ['POST']
      scopes: ['patients:create']

    - host: '*'
      paths: ['/users/patients']
      methods: ['GET']
      scopes: ['patients:readAll']

    - host: '*'
      paths: ['/users/patients/:patient_id']
      methods: ['GET']
      scopes: ['patients:read']

    - host: '*'
      paths: ['/users/patients/:patient_id']
      methods: ['PATCH']
      scopes: ['patients:update']

    ######################################

    ## ENDPOINTS TO MANAGE PILOT STUDIES ##
    - host: '*'
      paths: ['/pilotstudies']
      methods: ['POST']
      scopes: ['pilots:create']

    - host: '*'
      paths: ['/pilotstudies']
      methods: ['GET']
      scopes: ['pilots:readAll']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id']
      methods: ['GET']
      scopes: ['pilots:read']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id']
      methods: ['PATCH']
      scopes: ['pilots:update']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id']
      methods: ['DELETE']
      scopes: ['pilots:delete']
    ######################################

    ## ENDPOINTS TO GET PILOTSTUDIES ASSOCIED  ##
    - host: '*'
      paths: ['/users/healthprofessionals/:healthprofessional_id/pilotstudies']
      methods: ['GET']
      scopes: ['pilots:read']

    ## ENDPOINTS TO MANAGE HEALTH PROFESSIONS ASSOCIATION WITH A PILOT STUDY ##
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/healthprofessionals']
      methods: ['GET']
      scopes: ['healthprofessionals:read']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/healthprofessionals/:patient_id']
      methods: ['POST']
      scopes: ['pilots:update']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/healthprofessionals/:patient_id']
      methods: ['DELETE']
      scopes: ['pilots:update']
    ######################################

    ## ENDPOINTS TO MANAGE PATIENTS ASSOCIATION WITH A PILOT STUDY ##
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/patients']
      methods: ['GET']
      scopes: ['patients:read']
    ######################################


  ################ ACCOUNT API PRIVATE END #####################################

  ####### EHR API PRIVATE ########
  ehrPrivate:

    ## ENDPOINTS TO RECOVER THE LAST QUESTIONNAIRES ##
    - host: '*'
      paths: ['/patients/:patient_id/questionnaires/last']
      methods: ['GET']
      scopes: ['forms:read']
    ##################################################

    ## ENDPOINTS TO MANAGE SLEEPHABITS ##
    - host: '*'
      paths: ['/patients/:patient_id/sleephabits']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/sleephabits']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/sleephabits/:sleephabit_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/sleephabits/:sleephabit_id']
      methods: ['PATCH']
      scopes: ['forms:update']

    - host: '*'
      paths: ['/patients/:patient_id/sleephabits/:sleephabit_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE PHYSICALACTIVITYHABITS ##
    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits/:physicalactivityhabits_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits/:physicalactivityhabits_id']
      methods: ['PATCH']
      scopes: ['forms:update']

    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits/:physicalactivityhabits_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE FEEDINGHABITSRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords/:feedinghabitsrecord_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords/:feedinghabitsrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']

    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords/:feedinghabitsrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE MEDICALRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords/:medicalrecord_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords/:medicalrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']

    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords/:medicalrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE SOCIODEMOGRAPHICRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords/:sociodemographicrecord_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords/:sociodemographicrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']

    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords/:sociodemographicrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE FAMILYCOHESIONRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords/:familycohesionrecord_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords/:familycohesionrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']

    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords/:familycohesionrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE ORALHEALTHRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords/:oralhealthrecord_id']
      methods: ['GET']
      scopes: ['forms:read']

    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords/:oralhealthrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']

    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords/:oralhealthrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

  ############### EHR API PRIVATE END ##########################################

  ####### MHEALTH API PRIVATE ########
  mhealthPrivate:
    ## ENDPOINTS TO MANAGE MEASUREMENTS ##
    - host: '*'
      paths: ['/measurements']
      methods: ['GET']
      scopes: ['measurements:readAll']

    - host: '*'
      paths: ['/users/:user_id/measurements']
      methods: ['GET']
      scopes: ['measurements:read']

    - host: '*'
      paths: ['/users/:user_id/measurements']
      methods: ['POST']
      scopes: ['measurements:create']

    - host: '*'
      paths: ['/users/:user_id/measurements/:measurement_id']
      methods: ['GET']
      scopes: ['measurements:read']

    - host: '*'
      paths: ['/users/:user_id/measurements/:measurement_id']
      methods: ['DELETE']
      scopes: ['measurements:delete']
    ###############################

    ## ENDPOINTS TO MANAGE DEVICES ##
    - host: '*'
      paths: ['/users/:user_id/devices']
      methods: ['POST']
      scopes: ['devices:create']

    - host: '*'
      paths: ['/users/:user_id/devices']
      methods: ['GET']
      scopes: ['devices:read']

    - host: '*'
      paths: ['/users/:user_id/devices/:device_id']
      methods: ['GET']
      scopes: ['devices:read']

    - host: '*'
      paths: ['/users/:user_id/devices/:device_id']
      methods: ['DELETE']
      scopes: ['devices:delete']
    ###############################

  ############### MHEALTH API PRIVATE END ##########################################

  ####### ANALYTICS API PRIVATE ########
  analyticsPrivate:

    ## ENDPOINTS TO MANAGE EVALUATIONS ##
    # DEPRECATED
    # - host: '*'
    #   paths: ['/evaluations']
    #   methods: ['GET']
    #   scopes: ['evaluations:readAll']
    ###############################

    ## ENDPOINTS TO MANAGE NUTRITION EVALUATIONS ##
    # DEPRECATED
    # - host: '*'
    #   paths: ['/nutritional/evaluations']
    #   methods: ['GET']
    #   scopes: ['evaluations:readAll']

    ## ENDPOINTS TO MANAGE NUTRITIONAL EVALUATIONS ##
    - host: '*'
      paths: ['/patients/:patient_id/nutritional/evaluations']
      methods: ['POST']
      scopes: ['evaluations:create']

    - host: '*'
      paths: ['/patients/:patient_id/nutritional/evaluations']
      methods: ['GET']
      scopes: ['evaluations:read']

    - host: '*'
      paths: ['/patients/:patient_id/nutritional/evaluations/:evaluation_id']
      methods: ['GET']
      scopes: ['evaluations:read']

    - host: '*'
      paths: ['/patients/:patient_id/nutritional/evaluations/:evaluation_id']
      methods: ['DELETE']
      scopes: ['evaluations:delete']
    ####################################

    ## ENDPOINTS TO MANAGE COUNSELINGS FOR A NUTRITIONAL EVALUATIONS ##
    - host: '*'
      paths: ['/patients/:patient_id/nutritional/evaluations/:evaluation_id/counselings']
      methods: ['POST']
      scopes: ['evaluations:update']
    ####################################

    ## ENDPOINTS TO MANAGE NUTRITIONAL EVALUATIONS FOR A PILOTSTUDY ##
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/nutritional/evaluations']
      methods: ['GET']
      scopes: ['evaluations:read']
    ####################################

    ## ENDPOINTS TO MANAGE EVALUATIONS FOR A HEALTHPROFESSIONAL ##
    - host: '*'
      paths: ['/healthprofessionals/:healthprofessional_id/nutritional/evaluations']
      methods: ['GET']
      scopes: ['evaluations:read']
    ###############################

    ## ENDPOINTS TO MANAGE ODONTOLOGICAL EVALUATIONS FOR A PILOTSTUDY ##
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/odontological/evaluations']
      methods: ['POST']
      scopes: ['evaluations:create']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/odontological/evaluations']
      methods: ['GET']
      scopes: ['evaluations:read']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/odontological/evaluations/:evaluation_id']
      methods: ['GET']
      scopes: ['evaluations:read']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/odontological/evaluations/:evaluation_id']
      methods: ['DELETE']
      scopes: ['evaluations:delete']
    ####################################

  ############### ANALYTICS API PRIVATE END ##########################################


####### SERVICE ENDPOINTS DEFINITIONS ########
serviceEndpoints:
  accountService:
    url: ${ACCOUNT_SERVICE:-http://localhost:5000}

  ehrService:
    url: ${EHR_SERVICE:-http://localhost:3000}

  mhealthService:
    url: ${MHEALTH_SERVICE:-http://localhost:4000}

  analyticsService:
    url: ${ANALYTICS_SERVICE:-http://localhost:6000}

####### POLICIES USED IN PIPELINES DEFINITION ########
policies:
  - log
  - proxy
  - rate-limit
  - haniot-jwtScopes-policy
  - haniot-jwt-policy
  - haniot-auth-policy
  - haniot-body-parser-policy
  - haniot-delete-user-policy
  - odontological-evaluation-policy

####### PIPELINES DEFINITION ########
#### Pipeline no manage data coming from ACCOUNT PRIVATE and PUBLIC APIs ####
pipelines:

  ##################### PIPELINE PRIVATE ACCOUNT SERVICE ####################
  - name: privateAcountServicePipeline
    apiEndpoints:
      - accountPrivate
    policies:
      - haniot-body-parser-policy:
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - haniot-jwtScopes-policy:
      - haniot-delete-user-policy:
          - condition:
              name: 'regex-path-method'
              #regexpath é uma expressão regular
              regexpath: '^(\/users\/)[a-fA-F0-9]{24}$'
              method: 'DELETE'
            action:
              urldeleteservice: ${ACCOUNT_SERVICE:-http://localhost:5000}/users
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PUBLIC ACCOUNT SERVICE ####################
  - name: publicAccountServicePipeline
    apiEndpoints:
      - accountPublic
    policies:
      - haniot-body-parser-policy:
      - haniot-auth-policy:
          - condition:
              name: 'regex-path-method'
              #regexpath é uma expressão regular
              regexpath: '^(/auth)$'
              method: 'POST'
            action:
              urlauthservice: ${ACCOUNT_SERVICE:-http://localhost:5000}/auth
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PRIVATE EHR SERVICE ####################
  - name: privateEHRServicePipeline
    apiEndpoints:
      - ehrPrivate
    policies:
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - haniot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: ehrService
    ###########################################################################

  ##################### PIPELINE PRIVATE MHEALTH SERVICE ####################
  - name: privateMHEALTHServicePipeline
    apiEndpoints:
      - mhealthPrivate
    policies:
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - haniot-jwtScopes-policy:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: mhealthService
    ###########################################################################

    ##################### PIPELINE PRIVATE ANALYTIVS SERVICE ####################
  - name: privateAnalyticsServicePipeline
    apiEndpoints:
      - analyticsPrivate
    policies:
      - haniot-body-parser-policy:
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - haniot-jwtScopes-policy:
      - odontological-evaluation-policy:
          - condition:
              name: 'regex-path-method'
              #regexpath é uma expressão regular
              regexpath: '^(/pilotstudies/)[a-fA-F0-9]{24}(/odontological/evaluations)$'
              method: 'POST'
            action:
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true
              serviceEndpoint: analyticsService
    ###########################################################################
