http:
  port: ${PORT}
  hostname: 0.0.0.0
admin:
  port: ${ADMIN_PORT}
  hostname: 127.0.0.1

####### API ENDPOINTS DEFINITION ########
apiEndpoints:

####### ACCOUNT API PUBLIC ########
  accountPublic:  
    - host: '*'
      paths: ['/users/*/password']
      methods: ['PATCH']

####### ACCOUNT API PRIVATE ########
  accountPrivate:
    ## ENDPOINTS TO MANAGE USERS ##
    - host: '*'
      paths: ['/auth']
      methods: ['POST']

    - host: '*'
      paths: ['/users/admins']
      methods: ['POST']
      scopes: ['admin:create']

    - host: '*'
      paths: ['/users/healthprofessionals']
      methods: ['POST']
      scopes: ['healthprofessional:create'] 
    
    - host: '*'
      paths: ['/users/admins']
      methods: ['GET']
      scopes: ['admin:readAll']
    
    - host: '*'
      paths: ['/users/healthprofessionals']
      methods: ['GET']
      scopes: ['healthprofessional:readAll']

    - host: '*'
      paths: ['/users/admins/*']
      methods: ['GET']
      scopes: ['admin:read','admin:readAll']
    
    - host: '*'
      paths: ['/users/healthprofessionals/*']
      methods: ['GET']
      scopes: ['healthprofessional:read', 'healthprofessional:readAll']

    - host: '*'
      paths: ['/users/*']
      methods: ['DELETE']
      scopes: ['admin:delete','admin:deleteAll','healthprofessional:delete','healthprofessional:deleteAll']

    - host: '*'
      paths: ['/users/admins/*']
      methods: ['PATCH']
      scopes: ['admin:update','admin:updateAll']    
    
    - host: '*'
      paths: ['/users/healthprofessionals/*']
      methods: ['PATCH']
      scopes: ['healthprofessional:update', 'healthprofessional:updateAll']    
    ###############################

    ## ENDPOINTS TO MANAGE PILOT STUDIES ##
    - host: '*'
      paths: ['/pilotstudies']
      methods: ['POST']
      scopes: ['pilotstudy:create']

    - host: '*'
      paths: ['/pilotstudies']
      methods: ['GET']
      scopes: ['pilotstudy:readAll']

    - host: '*'
      paths: ['/pilotstudies/*']
      methods: ['GET']
      scopes: ['pilotstudy:read','pilotstudy:readAll']
    
    - host: '*'
      paths: ['/pilotstudies/*']
      methods: ['PATCH']
      scopes: ['pilotstudy:update', 'pilotstudy:updateAll']
    
    - host: '*'
      paths: ['/pilotstudies/*']
      methods: ['DELETE']
      scopes: ['pilotstudy:deleteAll']
    ######################################

    ## ENDPOINTS TO MANAGE HEALTH PROFESSIONS ASSOCIATION WITH A PILOT STUDY ##
    - host: '*'
      paths: ['/pilotstudies/*/healthprofessionals']
      methods: ['GET']
      scopes: ['pilotstudy:read', 'pilotstudy:readAll']

    - host: '*'
      paths: ['/pilotstudies/*/healthprofessionals/*']
      methods: ['POST']
      scopes: ['pilotstudy:create']    

    - host: '*'
      paths: ['/pilotstudies/*/healthprofessionals/*']
      methods: ['DELETE']
      scopes: ['pilotstudy:delete','pilotstudy:deleteAll']
    ######################################

################ ACCOUNT API PRIVATE END #####################################

####### EHR API PRIVATE ########
  ehrPrivate:
    ## ENDPOINTS TO MANAGE PATIENTS ##
    - host: '*'
      paths: ['/pilotstudies/*/patients']
      methods: ['POST']
      scopes: ['patient:create']

    - host: '*'
      paths: ['/pilotstudies/*/patients']
      methods: ['GET']
      scopes: ['patient:readAll'] 
    
    - host: '*'
      paths: ['/pilotstudies/*/patients/*']
      methods: ['GET']
      scopes: ['patient:read','patient:readAll'] 
    
    - host: '*'
      paths: ['/pilotstudies/*/patients/*']
      methods: ['PATCH']
      scopes: ['patient:update','patient:updateAll'] 
    
    - host: '*'
      paths: ['/pilotstudies/*/patients/*']
      methods: ['DELETE']
      scopes: ['patient:delete','patient:deleteAll']     
    
    ###############################

############### EHR API PRIVATE END ##########################################

####### SERVICE ENDPOINTS DEFINITIONS ########
serviceEndpoints:
  accountService:
    url: ${ACCOUNT_SERVICE}
  
  ehrService:
    url: ${EHR_SERVICE}

####### POLICIES USED IN PIPELINES DEFINITION ########
policies:
  - log
  - proxy
  - rate-limit
  - haniot-jwtScopes-policy
  - haniot-jwt-policy
  - haniot-auth-policy
  - haniot-body-parser-policy
  - haniot-delete-user-policy

####### PIPELINES DEFINITION ########
#### Pipeline no manage data coming from ACCOUNT PRIVATE and PUBLIC APIs ####
pipelines:

  ##################### PIPELINE PRIVATE ACCOUNT SERVICE ####################
  - name: privateAcountServicePipeline
    apiEndpoints:
      - accountPrivate
    policies: 
      - haniot-body-parser-policy:     
      - haniot-auth-policy:
        - 
          condition:
            name: 'is-auth'
            authpath: '/auth'
          action:
            urlauthservice: ${ACCOUNT_SERVICE}/auth
            secretOrPublicKey: ${SECRET_JWT}
            issuer: ${ISSUER}
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - haniot-jwtScopes-policy:
      - haniot-delete-user-policy:
        - 
          condition:
            name: 'is-delete'
            #deletepath é uma expressão regular
            deletepath: '^(\/users\/)[a-fA-F0-9]{24}$'
          action:
            urldeleteservice: ${ACCOUNT_SERVICE}/users            
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true 
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PUBLIC ACCOUNT SERVICE ####################
  - name: publicAccountServicePipeline
    apiEndpoints:
      - accountPublic
    policies:       
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true 
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PRIVATE EHR SERVICE ####################
  - name: privateEHRServicePipeline
    apiEndpoints:
      - ehrPrivate
    policies: 
      - haniot-body-parser-policy:          
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${SECRET_JWT}
              issuer: ${ISSUER}
      - haniot-jwtScopes-policy:           
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true 
              serviceEndpoint: ehrService
    ###########################################################################