http:
  port: ${PORT_HTTP:-8080}
  hostname: 0.0.0.0

####### API ENDPOINTS DEFINITION ########
apiEndpoints:

####### ACCOUNT API PUBLIC ########
  accountPublic:  
    - host: '*'
      paths: ['/users/:user_id/password']
      methods: ['PATCH']

    - host: '*'
      paths: ['/auth']
      methods: ['POST']
####### ACCOUNT API PUBLIC END ########

####### ACCOUNT API PRIVATE ########
  accountPrivate:
    ## ENDPOINTS TO MANAGE USERS ##
    - host: '*'
      paths: ['/users/admins']
      methods: ['POST']
      scopes: ['admins:create']

    - host: '*'
      paths: ['/users/admins']
      methods: ['GET']
      scopes: ['admins:readAll']
    
    - host: '*'
      paths: ['/users/admins/:admin_id']
      methods: ['GET']
      scopes: ['admins:read']
    
    - host: '*'
      paths: ['/users/admins/:admin_id']
      methods: ['PATCH']
      scopes: ['admins:update']  

    - host: '*'
      paths: ['/users/healthprofessionals']
      methods: ['POST']
      scopes: ['healthprofessionals:create']   
    
    - host: '*'
      paths: ['/users/healthprofessionals']
      methods: ['GET']
      scopes: ['healthprofessionals:readAll']

    - host: '*'
      paths: ['/users/healthprofessionals/:healthprofessional_id']
      methods: ['GET']
      scopes: ['healthprofessionals:read']
    
    - host: '*'
      paths: ['/users/healthprofessionals/:healthprofessional_id']
      methods: ['PATCH']
      scopes: ['healthprofessionals:update'] 

    - host: '*'
      paths: ['/users/:user_id']
      methods: ['DELETE']
      scopes: ['admins:delete','healthprofessionals:delete']    
    ###############################

    ## ENDPOINTS TO MANAGE PILOT STUDIES ##
    - host: '*'
      paths: ['/pilotstudies']
      methods: ['POST']
      scopes: ['pilots:create']

    - host: '*'
      paths: ['/pilotstudies']
      methods: ['GET']
      scopes: ['pilots:readAll']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id']
      methods: ['GET']
      scopes: ['pilots:read']
    
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id']
      methods: ['PATCH']
      scopes: ['pilots:update']
    
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id']
      methods: ['DELETE']
      scopes: ['pilots:deleteAll']
    ######################################
    
    ## ENDPOINTS TO GET PILOTSTUDIES ASSOCIED  ##
    - host: '*'
      paths: ['/users/healthprofessionals/:healthprofessional_id/pilotstudies']
      methods: ['GET']
      scopes: ['pilots:read']

    ## ENDPOINTS TO MANAGE HEALTH PROFESSIONS ASSOCIATION WITH A PILOT STUDY ##
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/healthprofessionals']
      methods: ['GET']
      scopes: ['healthprofessionals:read']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/healthprofessionals/:patient_id']
      methods: ['POST']
      scopes: ['pilots:update']    

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/healthprofessionals/:patient_id']
      methods: ['DELETE']
      scopes: ['pilots:update']
    ######################################

################ ACCOUNT API PRIVATE END #####################################

####### EHR API PRIVATE ########
  ehrPrivate:
    ## ENDPOINTS TO MANAGE PATIENTS ##
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/patients']
      methods: ['POST']
      scopes: ['patients:create']

    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/patients']
      methods: ['GET']
      scopes: ['patients:read'] 
    
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/patients/:patient_id']
      methods: ['GET']
      scopes: ['patients:read'] 
    
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/patients/:patient_id']
      methods: ['PATCH']
      scopes: ['patients:update'] 
    
    - host: '*'
      paths: ['/pilotstudies/:pilotstudy_id/patients/:patient_id']
      methods: ['DELETE']
      scopes: ['patients:delete']     
    
    ###############################

    ## ENDPOINTS TO MANAGE SLEEPHABITS ##
    - host: '*'
      paths: ['/patients/:patient_id/sleephabits']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/sleephabits']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/sleephabits/:sleephabit_id']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/sleephabits/:sleephabit_id']
      methods: ['PATCH']
      scopes: ['forms:update'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/sleephabits/:sleephabit_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE PHYSICALACTIVITYHABITS ##
    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits/:physicalactivityhabits_id']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits/:physicalactivityhabits_id']
      methods: ['PATCH']
      scopes: ['forms:update'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/physicalactivityhabits/:physicalactivityhabits_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE FEEDINGHABITSRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords']
      methods: ['GET']
      scopes: ['forms:read']
    
    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords/:feedinghabitsrecord_id']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords/:feedinghabitsrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/feedinghabitsrecords/:feedinghabitsrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE MEDICALRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords/:medicalrecord_id']
      methods: ['GET']
      scopes: ['forms:read']
    
    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords/:medicalrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']
    
    - host: '*'
      paths: ['/patients/:patient_id/medicalrecords/:medicalrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE SOCIODEMOGRAPHICRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords/:sociodemographicrecord_id']
      methods: ['GET']
      scopes: ['forms:read']
    
    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords/:sociodemographicrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/sociodemographicrecords/:sociodemographicrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE FAMILYCOHESIONRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords/:familycohesionrecord_id']
      methods: ['GET']
      scopes: ['forms:read']
    
    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords/:familycohesionrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']
    
    - host: '*'
      paths: ['/patients/:patient_id/familycohesionrecords/:familycohesionrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

    ## ENDPOINTS TO MANAGE ORALHEALTHRECORDS ##
    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords']
      methods: ['POST']
      scopes: ['forms:create']

    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords']
      methods: ['GET']
      scopes: ['forms:read'] 
    
    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords/:oralhealthrecord_id']
      methods: ['GET']
      scopes: ['forms:read']
    
    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords/:oralhealthrecord_id']
      methods: ['PATCH']
      scopes: ['forms:update']
    
    - host: '*'
      paths: ['/patients/:patient_id/oralhealthrecords/:oralhealthrecord_id']
      methods: ['DELETE']
      scopes: ['forms:delete']
    ###############################

############### EHR API PRIVATE END ##########################################

####### MHEALTH API PRIVATE ########
  mhealthPrivate:
    ## ENDPOINTS TO MANAGE DEVICES ##
    - host: '*'
      paths: ['/users/:user_id/devices']
      methods: ['POST']
      scopes: ['devices:create']

    - host: '*'
      paths: ['/users/:user_id/devices']
      methods: ['GET']
      scopes: ['devices:read'] 
    
    - host: '*'
      paths: ['/users/:user_id/devices/:device_id']
      methods: ['GET']
      scopes: ['devices:read'] 
    
    - host: '*'
      paths: ['/users/:user_id/devices/:device_id']
      methods: ['DELETE']
      scopes: ['devices:delete']       
    ###############################

    ## ENDPOINTS TO MANAGE MEASUREMENTS ##
    - host: '*'
      paths: ['/measurements']
      methods: ['GET']
      scopes: ['measurements:readAll'] 

    - host: '*'
      paths: ['/users/:user_id/measurements']
      methods: ['GET']
      scopes: ['measurements:read']     
   
    - host: '*'
      paths: ['/users/:user_id/measurements']
      methods: ['POST']
      scopes: ['measurements:create']
    
    - host: '*'
      paths: ['/users/:user_id/measurements/:measurement_id']
      methods: ['GET']
      scopes: ['measurements:read']
    
    - host: '*'
      paths: ['/users/:user_id/measurements/:measurement_id']
      methods: ['DELETE']
      scopes: ['measurements:delete']  
    ###############################

############### MHEALTH API PRIVATE END ##########################################


####### SERVICE ENDPOINTS DEFINITIONS ########
serviceEndpoints:
  accountService:
    url: ${ACCOUNT_SERVICE:-http://localhost:5000}
  
  ehrService:
    url: ${EHR_SERVICE:-http://localhost:3000}

  mhealthService:
    url: ${MHEALTH_SERVICE:-http://localhost:4000}

####### POLICIES USED IN PIPELINES DEFINITION ########
policies:
  - log
  - proxy
  - rate-limit
  - haniot-jwtScopes-policy
  - haniot-jwt-policy
  - haniot-auth-policy
  - haniot-body-parser-policy
  - haniot-delete-user-policy

####### PIPELINES DEFINITION ########
#### Pipeline no manage data coming from ACCOUNT PRIVATE and PUBLIC APIs ####
pipelines:

  ##################### PIPELINE PRIVATE ACCOUNT SERVICE ####################
  - name: privateAcountServicePipeline
    apiEndpoints:
      - accountPrivate
    policies: 
      - haniot-body-parser-policy:
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - haniot-jwtScopes-policy:
      - haniot-delete-user-policy:
        - 
          condition:
            name: 'is-delete'
            #deletepath é uma expressão regular
            deletepath: '^(\/users\/)[a-fA-F0-9]{24}$'
          action:
            urldeleteservice: ${ACCOUNT_SERVICE:-http://localhost:5000}/users
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true 
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PUBLIC ACCOUNT SERVICE ####################
  - name: publicAccountServicePipeline
    apiEndpoints:
      - accountPublic
    policies:
      - haniot-body-parser-policy:
      - haniot-auth-policy:
        - 
          condition:
            name: 'is-auth'
            authpath: '/auth'
          action:
            urlauthservice: ${ACCOUNT_SERVICE:-http://localhost:5000}/auth
            secretOrPublicKey: ${JWT_SECRET:-haniot123}
            issuer: ${ISSUER:-haniot}
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true 
              serviceEndpoint: accountService
  ###########################################################################

  ##################### PIPELINE PRIVATE EHR SERVICE ####################
  - name: privateEHRServicePipeline
    apiEndpoints:
      - ehrPrivate
    policies: 
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - haniot-jwtScopes-policy:    
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true 
              serviceEndpoint: ehrService
    ###########################################################################

  ##################### PIPELINE PRIVATE MHEALTH SERVICE ####################
  - name: privateMHEALTHServicePipeline
    apiEndpoints:
      - mhealthPrivate
    policies: 
      - haniot-jwt-policy:
          - action:
              secretOrPublicKey: ${JWT_SECRET:-haniot123}
              issuer: ${ISSUER:-haniot}
      - haniot-jwtScopes-policy:    
      - proxy:
          - action:
              prependPath:  true
              ignorePath:   false
              stripPath:    false
              changeOrigin: true 
              serviceEndpoint: mhealthService
    ###########################################################################