# Core
db:
  redis:
    emulate: ${EMULATE_REDIS}
    host: ${HOST_REDIS}
    port: ${PORT_REDIS}
    namespace: EG

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

plugins:
  eg-plugin-haniot:
    package: 'eg-plugin-haniot/manifest.js'
