# Core
db:
  redis:
    emulate: ${EMULATE_REDIS:-true}
    host: ${HOST_REDIS:-localhost}
    port: ${PORT_REDIS:-6379}
    namespace: haniot_gateway

plugins:
  express-apigw-base-plugin:
    package: express-apigw-base-plugin
